export const GET_SEARCHED_PRODUCTS = "GET_SEARCHED_PRODUCTS";
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCT_REVIEWS = "GET_PRODUCT_REVIEWS";

export const GET_CART = "GET_CART";

export const GET_MESSAGE = "GET_MESSAGE";
