export const GET_FULL_CATEGORIES = "GET_FULL_CATEGORIES";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const SET_CATEGORIES = "SET_CATEGORIES";
export const SET_SUBCATEGORIES = "SET_SUBCATEGORIES";
export const SET_DISHES = "SET_DISHES";

export const GET_CATEGORY = "GET_CATEGORY";
export const SET_PRODUCTS = "SET_PRODUCTS";
export const CLEAR_PRODUCTS = "CLEAR_PRODUCTS";
export const GET_MORE_PRODUCTS = "GET_MORE_PRODUCTS";
export const GET_SEARCHED_PRODUCTS = "GET_SEARCHED_PRODUCTS";
export const CLEAR_SEARCHED_PRODUCTS = "CLEAR_SEARCHED_PRODUCTS";
export const SET_PRODUCT = "SET_PRODUCT";
export const GET_PRODUCT_ID = "GET_PRODUCT_ID";
export const GET_PRODUCT_REVIEWS = "GET_PRODUCT_REVIEWS";
export const ADD_PRODUCT_REVIEW = "ADD_PRODUCT_REVIEW";
export const PRODUCTS_END = "PRODUCTS_END";

export const GET_CART = "GET_CART";
export const SET_CART = "SET_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const CHANGE_CART = "CHANGE_CART";
export const CART_FETCHED = "CART_FETCHED";
export const CART_FETCHING = "CART_FETCHING";

export const GET_ORDER = "GET_ORDER";
export const SET_ORDER = "SET_ORDER";

export const LOG_IN = "LOG_IN";
export const SET_TOKEN = "SET_TOKEN";
export const GET_TOKEN = "GET_TOKEN";
export const GET_USER = "GET_USER";
export const SET_USER = "SET_USER";
export const UPDATE_USER = "UPDATE_USER";

export const FETCHING = "FETCHING";
export const FETCHED = "FETCHED";
export const GET_MESSAGE = "GET_MESSAGE";
export const GET_AUTOCOMPLETE = "GET_AUTOCOMPLETE";
export const GET_LETTERS = "GET_LETTERS";

export const GET_DELIVERY_COST = "GET_DELIVERY_COST";
export const SET_DELIVERY_COST = "SET_DELIVERY_COST";
export const GET_DELIVERY_COST_SINGLE = "GET_DELIVERY_COST_SINGLE";
export const SET_MASS_DELIVERY_COST = "SET_MASS_DELIVERY_COST";

export const SET_LANG = "SET_LANG";
export const GET_LANG = "GET_LANG";
export const SET_SEARCH = "SET_SEARCH";
export const GET_SEARCH = "GET_SEARCH";
export const GET_SEARCH_FOCUS = "GET_SEARCH_FOCUS";
