export const GET_FULL_CATEGORIES = "GET_FULL_CATEGORIES";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_SUBCATEGORIES = "GET_SUBCATEGORIES";
export const GET_DISHES = "GET_DISHES";

export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_MORE_PRODUCTS = "GET_MORE_PRODUCTS";
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCT_REVIEWS = "GET_PRODUCT_REVIEWS";

export const GET_CART = "GET_CART";

export const GET_MESSAGE = "GET_MESSAGE";
export const GET_AUTOCOMPLETE = "GET_AUTOCOMPLETE";
export const GET_LETTERS = "GET_LETTERS";
export const GET_DELIVERY_COST = "GET_DELIVERY_COST";
export const SET_LANG = "SET_LANG";
export const SET_SEARCH = "SET_SEARCH";
export const GET_SEARCH_FOCUS = "GET_SEARCH_FOCUS";
